### ISSUE TITLE
Add limit on number of points user can introduce into the system

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack-guilds#45]
To prevent abuse of the system (perhaps accidental too), we don't want users to be able to introduce too many points into the system (e.g. sponsors). There should be a limit to the number of points that can be redeemed from particular users.
Relationally, this would be calculated as follows: _(`->` = "has")_
`SUM OF Point -> qrcode: QRCode -> creator: User -> user_id =? LIMITED_USER_ID`

**Comment by Lordfirespeed** [comment]
This is effectively implemented by the challenge/quests rework 2024
